ChouettesBundle\Entity\Whoami:
    type: entity
    table: null
    repositoryClass: ChouettesBundle\Repository\WhoamiRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text

    manyToOne:
        image:
            targetEntity: ChouettesBundle\Entity\Image
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }
