ChouettesBundle\Entity\Categorie:
    type: entity
    table: null
    repositoryClass: ChouettesBundle\Repository\CategorieRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255

    lifecycleCallbacks: {  }
